[pytest]
testpaths = leagueoptimizer/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = --verbose --cov=leagueoptimizer --cov-report=term-missing
markers =
    unit: mark a test as a unit test
    integration: mark a test as an integration test
    slow: mark a test as slow
    api: mark a test as requiring API access 